### ISSUE TITLE
The java program doesn't work well or i am stupid?

### ISSUE THREAD

**Issue by thangvu97** [rgerganov/dlp#1]
I tried the java program  with g=5, p=0x30 = 48 , A =0x19 = 25.
g^a mod p = A  ===> 5^a mod 48 = 25 ====> a = 2.
But the program calculated a = 46338. Is there something wrong or i'm missing something?
Can you help me with g=5, p=2161DA74D0E4E12B9D4DB244233DE365DD089F66B1F82C40FDD23B53CE74F, A=1CF55A6F34457ABA50987D7791438FCA41BCCD14335BD53BBA2D6B2693DA1? Thank you!

**Comment by rgerganov** [comment]
> I tried the java program with g=5, p=0x30 = 48 , A =0x19 = 25. g^a mod p = A ===> 5^a mod 48 = 25 ====> a = 2. But the program calculated a = 46338. Is there something wrong or i'm missing something? 

a=46338 is a correct solution:

```
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 5**46338 % 48
25
>>> 
```

> Can you help me with g=5, p=2161DA74D0E4E12B9D4DB244233DE365DD089F66B1F82C40FDD23B53CE74F, A=1CF55A6F34457ABA50987D7791438FCA41BCCD14335BD53BBA2D6B2693DA1? Thank you!

My program solves DLP when `a` is 32bit number. If it doesn't find solution then it is a larger number.
